### ISSUE TITLE
Add feature to increase the cursor caret

### ISSUE THREAD

**Issue by shibbirweb** [shibbirweb/vs-code-extra-cursor-caret-height#2]
The snippet of solution

```css
 .monaco-editor .cursor {
  padding-top: 15px !important;
  padding-bottom: 15px !important;
  margin-top: -15px !important;
  box-sizing: content-box !important;
}
```
